### ISSUE TITLE
ReferenceError: protocol is not defined

### ISSUE THREAD

**Issue by cbieser** [liveblog/liveblog#1267]
I'm following https://wiki.sourcefabric.org/display/LIVEBLOG/Themes+-+the+theme+generator

When running `gulp watch-static --embedUrl=https://<removed>-api.liveblog.pro/api/client_blogs/<removed>/posts` i've got `ReferenceError: protocol is not defined`.

```
[08:49:37] Using gulpfile <removed>\gulpfile.js
[08:49:37] Starting 'install'...
[08:49:37] ATTENTION: Make sure you ran gulp wire-deps before install step
[08:49:37] Finished 'install' after 31 ms
[08:49:37] Starting 'precomp-parent-templates'...
[08:49:37] Starting 'precomp-theme-templates'...
[08:49:37] Finished 'precomp-theme-templates' after 6.04 ms
[08:49:37] Starting 'clean-js'...
[08:49:37] Starting 'clean-css'...
[08:49:37] Finished 'clean-js' after 33 ms
[08:49:37] Starting 'browserify'...
[08:49:37] Finished 'clean-css' after 132 ms
[08:49:37] Starting 'less'...
[08:49:40] Finished 'less' after 3.14 s
[08:49:40] Finished 'precomp-parent-templates' after 3.47 s
[08:49:40] Starting 'bundle-templates'...
[08:49:40] Finished 'bundle-templates' after 48 μs
[08:49:49] Finished 'browserify' after 12 s
[08:49:49] Starting 'bundlejs'...
[08:49:50] Finished 'bundlejs' after 127 ms
[08:49:50] Starting 'index-inject'...
[08:49:50] 'index-inject' errored after 5.18 ms
[08:49:50] ReferenceError: protocol is not defined
    at Gulp.<anonymous> (<removed>\node_modules\liveblog-default-theme\tasks\injecting.js:23:38)
    at module.exports (<removed>\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (<removed>\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (<removed>\node_modules\orchestrator\index.js:214:10)
    at <removed>\node_modules\orchestrator\index.js:279:18
    at finish (<removed>\node_modules\orchestrator\lib\runTask.js:21:8)
    at <removed>\node_modules\orchestrator\lib\runTask.js:52:4
    at f (<removed>\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.onend (<removed>\node_modules\end-of-stream\index.js:31:18)
    at DestroyableTransform.emit (events.js:203:15)
npm WARN swr-basic-theme@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 14686 packages in 10.92s
found 23 vulnerabilities (7 low, 4 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Process finished with exit code 1
```

Windows 10 1709
node v10.16.0
npm v6.11.3

**Comment by cbieser** [comment]
Currently I use local data i've exported from the API to the test/api_response.json and text/options.json files.

**Comment by eos87** [comment]
Hi @cbieser, I'm providing a fix for this in #1268 which will be released soon. 

In the meantime, I've published a beta version of Default SEO Theme with this fix included so you can continue working with your custom theme https://www.npmjs.com/package/liveblog-default-theme/v/3.5.12-beta 
You need to update the dependency version in the theme's `package.json` file and run `npm install`, I think that should do the trick. 

Please have a look and let me know if it works :)

**Comment by cbieser** [comment]
Hi @eos87 
there are no more errors, thanks for fixing it. From the output:
```
{ apiHost: '', protocol: '', blogId: '' }
```
However, there is only the content from the test folder. I had expected something different.

**Comment by eos87** [comment]
Hi @cbieser, I think you have a little error in the command, try running it like this:
```gulp watch-static --embedUrl https://<removed>-api.liveblog.pro/api/client_blogs/<removed>/posts``` 
notice that I've removed the `=` after `--embedUrl` param.

**Comment by cbieser** [comment]
Many thanks @eos87, now it works as expected.
