### ISSUE TITLE
Template render error: (template-post.html)

### ISSUE THREAD

**Issue by cbieser** [liveblog/liveblog#1269]
Hi @eos87 i think there is a new error in ^3.5.10. Yesterday our liveblog-instance was updated and the theme also from 3.5.8 to 3.5.10. The error also accoured local before our liveblog-instance was updated.

My Theme only contains additional-css rules, no html-files (okay, the unmodified `/template.html`)

The error is thrown in the browser console when loading more items
```
Handler error:  Template render error: (template-post.html)
  Template render error: (template-post.html) [Line 62, Column 5]
  TypeError: n.fromIterator is not a function
    at Object.t.prettifyError (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:16681)
    at https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:24491
    at d.e [as rootRenderFunc] (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:5:4316)
    at d.render (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:24432)
    at https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:22654
    at c (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:21827)
    at i (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:21930)
    at https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:21997
    at n (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:18573)
    at Object.t.asyncIter (https://<removed>.liveblog.pro/lb-<removed>/0.1.18/liveblog-<removed>-theme/dist/liveblog-<removed>-theme-08da4afe0c.js:7:18600) 
```

**Comment by eos87** [comment]
Hi @cbieser, could you try removing `node_modules` in your theme, double check dependency version and run `npm install` again. Then `make` to generate a new theme zip to check if it works fine?

**Comment by cbieser** [comment]
Hi @eos87, after removing `package-lock.json` additionally it seems to work. Thank you!
