### ISSUE TITLE
Error during configuration of the server

### ISSUE THREAD

**Issue by Hack4Life** [liveblog/liveblog#1331]
Hi! 
I am following the guide and when executing the following command:
`pip install -r requirements.txt` (inside the virtual env [as described](https://github.com/liveblog/liveblog#configure-the-server)) 
I get the following error messages: 
```
ERROR: eve 0.7.8 has requirement flask<=0.12,>=0.10.1, but you'll have flask 1.0 which is incompatible.
ERROR: eve 0.7.8 has requirement itsdangerous<1.0,>=0.24, but you'll have itsdangerous 2.0.1 which is incompatible.
ERROR: eve 0.7.8 has requirement jinja2<3.0,>=2.8, but you'll have jinja2 3.0.1 which is incompatible.
ERROR: eve 0.7.8 has requirement markupsafe<1.0,>=0.23, but you'll have markupsafe 2.0.1 which is incompatible.
ERROR: eve 0.7.8 has requirement werkzeug<=0.11.15,>=0.9.4, but you'll have werkzeug 0.16.1 which is incompatible.
ERROR: eve-elastic 2.4.1 has requirement elasticsearch<3.0.0,>=2.0.0, but you'll have elasticsearch 1.9.0 which is incompatible.
ERROR: flask-oauthlib 0.9.6 has requirement oauthlib!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2, but you'll have oauthlib 3.1.1 which is incompatible.
ERROR: flask-oauthlib 0.9.6 has requirement requests-oauthlib<1.2.0,>=0.6.2, but you'll have requests-oauthlib 1.3.0 which is incompatible.
```

when I execute the next command (`python3 manage.py app:initialize_data;`) I get the following errors:
```
manage.py:6: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  from flask.ext.script import Manager
/var/www/liveblog/server/env/src/superdesk-core/superdesk/celery_app.py:37: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is None or isinstance(v, bool) or v is 0:
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from app import get_app
  File "/var/www/liveblog/server/app.py", line 18, in <module>
    from liveblog.blogs import bloglist_assets_blueprint, bloglist_blueprint
  File "/var/www/liveblog/server/liveblog/blogs/__init__.py", line 2, in <module>
    from .blogs import BlogService, BlogsResource, UserBlogsResource, UserBlogsService
  File "/var/www/liveblog/server/liveblog/blogs/blogs.py", line 19, in <module>
    from superdesk.activity import add_activity
  File "/var/www/liveblog/server/env/src/superdesk-core/superdesk/activity.py", line 21, in <module>
    from superdesk.notification import push_notification
  File "/var/www/liveblog/server/env/src/superdesk-core/superdesk/notification.py", line 20, in <module>
    from superdesk.websockets_comms import SocketMessageProducer
  File "/var/www/liveblog/server/env/src/superdesk-core/superdesk/websockets_comms.py", line 16, in <module>
    import websockets
  File "/var/www/liveblog/server/env/lib/python3.8/site-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/var/www/liveblog/server/env/lib/python3.8/site-packages/websockets/client.py", line 20, in <module>
    from .protocol import WebSocketCommonProtocol
  File "/var/www/liveblog/server/env/lib/python3.8/site-packages/websockets/protocol.py", line 18, in <module>
    from .compatibility import asyncio_ensure_future
  File "/var/www/liveblog/server/env/lib/python3.8/site-packages/websockets/compatibility.py", line 15
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                    ^
SyntaxError: invalid syntax
```

Of course the following commands have been set before installing the requirements.txt file:
```
pip install 'pip<=20.2.3'
pip install 'setuptools<50'
```

Any help is highly appreciated! 

BR from Austria,
Fabian

**Comment by eos87** [comment]
Hi @Hack4Life, I totally missed this one. I think the problem here is your python version. You probably have figured that out already but just in case. Use Python `v3.6.x` and that should solve the issue.
