### ISSUE TITLE
Docker build error installing grunt-cli

### ISSUE THREAD

**Issue by masterxavierfox** [liveblog/liveblog#918]
I get the following error when running a docker build:
```
`Step 4 : RUN npm -g install grunt-cli
 ---> Running in c1883cbc7942

/usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:37:17
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)
`
```
I have tried the following solution but it didn't worked.

https://github.com/npm/npm/issues/17996

im running the setup on ubuntu 16.

**Comment by eos87** [comment]
Closing as we're not supporting docker installation at the moment. Any PR with help is welcome.
